#!/bin/bash
#Java builder WAR

#megam_java_builder/build tomcat build_ci=true megam_home=/var/lib/megam/gulp project=orion local_repo=/home/megam/tomcat/webapps remote_repo=https://github.com/thomasalrin/orion.git


for i in "$@"
do
case $i in
    project=*)
    project="${i#*=}"

    ;;
    local_repo=*)
    local_repo="${i#*=}"
    ;;
    remote_repo=*)
    remote_repo="${i#*=}"
    ;;
    megam_home=*)
    megam_home="${i#*=}"
    ;;
    build_ci=*)
    build_ci="${i#*=}"
    ;;

esac
done

filename=$(basename "$remote_repo")
extension="${filename##*.}"
filename="${filename%.*}"

case "$extension" in

git)  cd $local_repo
      rm *.war
      cd $megam_home

      case $build_ci in
      true)
      rm -r $filename
      git clone $remote_repo
      cd $filename

        ;;
      false)
      cd $filename
        ;;
      esac
      mvn clean
      mvn package -Dmaven.test.skip=true
      done
      ;;
esac

stop java
start java

