#!/bin/bash
#Java builder WAR

#megam_java_builder/build tomcat megam_home=/var/lib/megam/gulp project=orion local_repo=/home/megam/tomcat/webapps remote_repo=https://github.com/thomasalrin/orion.git


for i in "$@"
do
case $i in
    project=*)
    project="${i#*=}"

    ;;
    local_repo=*)
    local_repo="${i#*=}"
    ;;
    remote_repo=*)
    remote_repo="${i#*=}"
    ;;
    megam_home=*)
    megam_home="${i#*=}"
    ;;

esac
done

filename=$(basename "$remote_repo")
extension="${filename##*.}"
filename="${filename%.*}"

case "$extension" in

war)  cd $local_repo
      rm *.war
      rm -r $project
      wget $remote_repo
      chown -R megam:megam *.war
      ;;
git)  cd $local_repo
      rm *.war
      cd $megam_home
      rm -r $filename
      git clone $remote_repo
      cd $filename
      mvn clean
      mvn package -Dmaven.test.skip=true
      arr=$(find . -path "**/target/*.war")
      for i in "${arr[@]}" 
      do
      cp target/*.war $local_repo
      chown -R megam:megam $local_repo/*.war
      done
      ;;
esac

stop java
start java

