#!/bin/bash
#Java builder WAR

#megam_java_builder/build tomcat build_ci=true  project=orion  remote_repo=https://github.com/thomasalrin/java-spring-petclinic.git

build_ci=true
local_repo=/home/megam/tomcat/webapps
megam_home=/var/lib/megam/gulp

for i in "$@"
do
case $i in
    project=*)
    project="${i#*=}"

    ;;
    local_repo=*)
    local_repo="${i#*=}"
    ;;
    remote_repo=*)
    remote_repo="${i#*=}"
    ;;
    megam_home=*)
    megam_home="${i#*=}"
    ;;
    build_ci=*)
    build_ci="${i#*=}"
    ;;

esac
done

filename=$(basename "$remote_repo")
extension="${filename##*.}"
filename="${filename%.*}"

case "$extension" in

git)  cd $megam_home

      case $build_ci in
      true)
      rm -r $filename
      git clone $remote_repo
      cd $filename
      mvn clean
      mvn install -Dmaven.test.skip=true -U
      stop java
      start java 
        ;;
      false)
      cd $filename
      mvn clean
      mvn install -Dmaven.test.skip=true -U
        ;;
      esac
      ;;
esac

