#!/bin/bash
#Nodejs builder Git

#megam_nodejs_builder/build nodejs project=ghost local_repo=/home/sandbox/ghost remote_repo=https://github.com/thomasalrin/ghost.git

megam_home=/var/lib/megam/gulp
build_ci=true


for i in "$@"
do
case $i in
    project=*)
    project="${i#*=}"

    ;;
    local_repo=*)
    local_repo="${i#*=}"
    ;;
    remote_repo=*)
    remote_repo="${i#*=}"
    ;;
esac
done

filename=$(basename "$remote_repo")
extension="${filename##*.}"
project="${filename%.*}"

stop nodejs
cd $megam_home
case $build_ci in
true)
    rm -r $project
    git clone $remote_repo
    cd $filename
    ;;
false)
    cd $filename
    ;;
esac
    npm install
    #npm install forever-monitor
start nodejs
