#!/bin/bash
#Nodejs builder Git

#megam_nodejs_builder/build nodejs project=ghost local_repo=/home/sandbox/ghost remote_repo=https://github.com/thomasalrin/ghost.git

megam_home=/var/lib/megam/gulp
build_ci=true

for i in "$@"
do
case $i in
    local_repo=*)
    local_repo="${i#*=}"
    ;;
    remote_repo=*)
    remote_repo="${i#*=}"
    ;;
    megam_home=*)
    megam_home="${i#*=}"
    ;;
    build_ci=*)
    build_ci="${i#*=}"
    ;;
esac
done

filename=$(basename "$remote_repo")
extension="${filename##*.}"
project="${filename%.*}"


case $build_ci in
true)
    stop nodejs
    cd $megam_home
    rm -r $project
    git clone $remote_repo
    cd $project
    npm install
    #npm install forever-monitor
    chmod 755 ./start
    ./start
    start nodejs
    ;;
esac
